import type { InvestorProfile, IndicatorConfigInput, ScoreThresholdInput, SectorFactorWeightInput } from "../types";

export const DEFAULT_INDICATORS: Record<InvestorProfile, IndicatorConfigInput[]> = {
  GENERICO: [
    { indicatorId: "pl",             category: "FUNDAMENTALISTA", weight: 20, idealRange: "8–15"    },
    { indicatorId: "pvp",            category: "FUNDAMENTALISTA", weight: 15, idealRange: "0.8–2.0" },
    { indicatorId: "roe",            category: "FUNDAMENTALISTA", weight: 20, idealRange: "10–20%"  },
    { indicatorId: "margemLiquida",  category: "FUNDAMENTALISTA", weight: 15, idealRange: "8–20%"   },
    { indicatorId: "dividaEbitda",   category: "FUNDAMENTALISTA", weight: 15, idealRange: "0–0.8x"  },
    { indicatorId: "earningsGrowth", category: "FUNDAMENTALISTA", weight: 15, idealRange: "5–12%"   },
  ],
  CONSERVADOR: [
    { indicatorId: "pl",             category: "FUNDAMENTALISTA", weight: 12, idealRange: "6–12"    },
    { indicatorId: "pvp",            category: "FUNDAMENTALISTA", weight:  8, idealRange: "0.8–1.8" },
    { indicatorId: "roe",            category: "FUNDAMENTALISTA", weight: 13, idealRange: "15–25%"  },
    { indicatorId: "margemLiquida",  category: "FUNDAMENTALISTA", weight:  8, idealRange: "10–25%"  },
    { indicatorId: "dividaEbitda",   category: "FUNDAMENTALISTA", weight:  8, idealRange: "0–0.6x"  },
    { indicatorId: "earningsGrowth", category: "FUNDAMENTALISTA", weight:  8, idealRange: "6–12%"   },
    { indicatorId: "dividendYield",  category: "FUNDAMENTALISTA", weight:  8, idealRange: "4–8%"    },
    { indicatorId: "rsi",            category: "TECNICO",         weight:  6, idealRange: "45–60"   },
    { indicatorId: "precoVsMMs",     category: "TECNICO",         weight:  5, idealRange: "≥MM50"   },
    { indicatorId: "macd",           category: "TECNICO",         weight:  5, idealRange: "Positivo" },
    { indicatorId: "tendencia",      category: "TECNICO",         weight:  4, idealRange: "Alta/Lateral" },
    { indicatorId: "volatilidade",   category: "RISCO",           weight:  6, idealRange: "Baixa"   },
    { indicatorId: "drawdown",       category: "RISCO",           weight:  5, idealRange: "≤20%"    },
    { indicatorId: "beta",           category: "RISCO",           weight:  4, idealRange: "0.7–1.0" },
  ],
  MODERADO: [
    { indicatorId: "pl",             category: "FUNDAMENTALISTA", weight: 10, idealRange: "8–18"    },
    { indicatorId: "pvp",            category: "FUNDAMENTALISTA", weight:  6, idealRange: "0.8–2.5" },
    { indicatorId: "roe",            category: "FUNDAMENTALISTA", weight: 10, idealRange: "12–25%"  },
    { indicatorId: "margemLiquida",  category: "FUNDAMENTALISTA", weight:  6, idealRange: "8–25%"   },
    { indicatorId: "dividaEbitda",   category: "FUNDAMENTALISTA", weight:  6, idealRange: "0–1.0x"  },
    { indicatorId: "earningsGrowth", category: "FUNDAMENTALISTA", weight: 10, idealRange: "8–15%"   },
    { indicatorId: "dividendYield",  category: "FUNDAMENTALISTA", weight:  6, idealRange: "3–7%"    },
    { indicatorId: "rsi",            category: "TECNICO",         weight:  8, idealRange: "40–65"   },
    { indicatorId: "precoVsMMs",     category: "TECNICO",         weight:  6, idealRange: "≥MM20"   },
    { indicatorId: "macd",           category: "TECNICO",         weight:  6, idealRange: "Pos/Neutro" },
    { indicatorId: "tendencia",      category: "TECNICO",         weight:  6, idealRange: "Alta"     },
    { indicatorId: "breakout",       category: "TECNICO",         weight:  5, idealRange: "Próximo"  },
    { indicatorId: "volatilidade",   category: "RISCO",           weight:  6, idealRange: "Média"    },
    { indicatorId: "drawdown",       category: "RISCO",           weight:  5, idealRange: "≤30%"     },
    { indicatorId: "beta",           category: "RISCO",           weight:  4, idealRange: "0.8–1.2"  },
  ],
  AGRESSIVO: [
    { indicatorId: "pl",             category: "FUNDAMENTALISTA", weight:  7, idealRange: "10–30"   },
    { indicatorId: "pvp",            category: "FUNDAMENTALISTA", weight:  4, idealRange: "1.0–4.0" },
    { indicatorId: "roe",            category: "FUNDAMENTALISTA", weight:  7, idealRange: "8–30%"   },
    { indicatorId: "margemLiquida",  category: "FUNDAMENTALISTA", weight:  4, idealRange: "5–30%"   },
    { indicatorId: "dividaEbitda",   category: "FUNDAMENTALISTA", weight:  4, idealRange: "0–2.0x"  },
    { indicatorId: "earningsGrowth", category: "FUNDAMENTALISTA", weight: 13, idealRange: "12–30%"  },
    { indicatorId: "dividendYield",  category: "FUNDAMENTALISTA", weight:  3, idealRange: "0–5%"    },
    { indicatorId: "rsi",            category: "TECNICO",         weight: 11, idealRange: "30–70"   },
    { indicatorId: "precoVsMMs",     category: "TECNICO",         weight:  9, idealRange: "≥MM20"   },
    { indicatorId: "macd",           category: "TECNICO",         weight:  7, idealRange: "Qualquer" },
    { indicatorId: "tendencia",      category: "TECNICO",         weight:  9, idealRange: "Alta/Explosiva" },
    { indicatorId: "breakout",       category: "TECNICO",         weight:  7, idealRange: "Confirmado" },
    { indicatorId: "volatilidade",   category: "RISCO",           weight:  5, idealRange: "Alta"    },
    { indicatorId: "drawdown",       category: "RISCO",           weight:  5, idealRange: "≤45%"    },
    { indicatorId: "beta",           category: "RISCO",           weight:  5, idealRange: "1.0–2.0" },
  ],
};

export const DEFAULT_THRESHOLDS: Record<InvestorProfile, ScoreThresholdInput[]> = {
  GENERICO: [
    { minScore: 80, decision: "COMPRA_FORTE", emoji: "🚀", desc: "Fundamentos excelentes — forte oportunidade de compra" },
    { minScore: 65, decision: "COMPRA",       emoji: "✅", desc: "Bons fundamentos — ativo com potencial de valorização" },
    { minScore: 45, decision: "MANTER",       emoji: "⏸️", desc: "Fundamentos razoáveis — aguardar confirmação" },
    { minScore: 30, decision: "VENDA",        emoji: "⚠️", desc: "Fundamentos fracos — considerar reduzir posição" },
    { minScore:  0, decision: "VENDA_FORTE",  emoji: "🔴", desc: "Fundamentos ruins — sair do ativo" },
  ],
  CONSERVADOR: [
    { minScore: 85, decision: "COMPRA_FORTE", emoji: "🚀", desc: "Ativo seguro com excelente relação risco/retorno" },
    { minScore: 70, decision: "COMPRA",       emoji: "✅", desc: "Ativo com perfil conservador bem avaliado" },
    { minScore: 50, decision: "MANTER",       emoji: "⏸️", desc: "Qualidade razoável — manter posição existente" },
    { minScore: 35, decision: "VENDA",        emoji: "⚠️", desc: "Risco elevado para perfil conservador" },
    { minScore:  0, decision: "VENDA_FORTE",  emoji: "🔴", desc: "Não recomendado para perfil conservador" },
  ],
  MODERADO: [
    { minScore: 80, decision: "COMPRA_FORTE", emoji: "🚀", desc: "Fundamentos e técnica alinhados — forte oportunidade" },
    { minScore: 60, decision: "COMPRA",       emoji: "✅", desc: "Boa relação fundamentos/momentum — oportunidade de entrada" },
    { minScore: 40, decision: "MANTER",       emoji: "⏸️", desc: "Sinais mistos — aguardar convergência de indicadores" },
    { minScore: 25, decision: "VENDA",        emoji: "⚠️", desc: "Deterioração de fundamentos e/ou técnica — reduzir" },
    { minScore:  0, decision: "VENDA_FORTE",  emoji: "🔴", desc: "Fundamentos e técnica deteriorados — sair" },
  ],
  AGRESSIVO: [
    { minScore: 75, decision: "COMPRA_FORTE", emoji: "🚀", desc: "Momentum forte com crescimento acelerado — máxima convicção" },
    { minScore: 55, decision: "COMPRA",       emoji: "✅", desc: "Tendência positiva com bom crescimento — comprar" },
    { minScore: 35, decision: "MANTER",       emoji: "⏸️", desc: "Momentum enfraquecendo — aguardar novo sinal" },
    { minScore: 20, decision: "VENDA",        emoji: "⚠️", desc: "Perda de momentum — reduzir posição" },
    { minScore:  0, decision: "VENDA_FORTE",  emoji: "🔴", desc: "Tendência negativa confirmada — sair imediatamente" },
  ],
};

export const DEFAULT_SECTOR_FACTOR_WEIGHTS: Record<InvestorProfile, SectorFactorWeightInput[]> = {
  GENERICO: [
    { factor: "valor",       weight: 0.30 },
    { factor: "qualidade",   weight: 0.30 },
    { factor: "momentum",    weight: 0.15 },
    { factor: "crescimento", weight: 0.25 },
  ],
  CONSERVADOR: [
    { factor: "valor",       weight: 0.35 },
    { factor: "qualidade",   weight: 0.40 },
    { factor: "momentum",    weight: 0.05 },
    { factor: "crescimento", weight: 0.20 },
  ],
  MODERADO: [
    { factor: "valor",       weight: 0.30 },
    { factor: "qualidade",   weight: 0.30 },
    { factor: "momentum",    weight: 0.15 },
    { factor: "crescimento", weight: 0.25 },
  ],
  AGRESSIVO: [
    { factor: "valor",       weight: 0.20 },
    { factor: "qualidade",   weight: 0.25 },
    { factor: "momentum",    weight: 0.25 },
    { factor: "crescimento", weight: 0.30 },
  ],
};
